# Generated by Django 4.0.5 on 2022-08-19 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('short_description', models.CharField(max_length=200, null=True)),
                ('long_description', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Homework', 'Homework'), ('Group Project', 'Group Project')], max_length=200, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('deadline', models.DateTimeField(null=True)),
                ('status', models.CharField(max_length=200, null=True)),
                ('quickA', models.BooleanField(default=b'I01\n')),
                ('course', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.course')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('short_description', models.CharField(max_length=200, null=True)),
                ('long_description', models.CharField(max_length=1000, null=True)),
                ('video', models.CharField(max_length=1000, null=True)),
                ('video_description', models.CharField(max_length=2000, null=True)),
                ('contents', models.CharField(max_length=2000, null=True)),
                ('course', models.ForeignKey(db_column='course_lesson', on_delete=django.db.models.deletion.CASCADE, to='main.course')),
            ],
        ),
    ]
