# Generated by Django 4.0.5 on 2022-08-26 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_student_tasks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Solutions',
            new_name='TaskStudent',
        ),
    ]
