# Generated by Django 4.0.5 on 2022-08-26 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_solutions_taskstudent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='course',
        ),
        migrations.RemoveField(
            model_name='task',
            name='quickA',
        ),
        migrations.RemoveField(
            model_name='task',
            name='solution',
        ),
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
        migrations.AddField(
            model_name='taskstudent',
            name='quickA',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='taskstudent',
            name='status',
            field=models.CharField(default='NEW', max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution', models.FileField(blank=True, null=True, upload_to='')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.task')),
            ],
        ),
    ]
