# Generated by Django 4.0.5 on 2022-08-21 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='tasks',
            field=models.ManyToManyField(to='main.task'),
        ),
    ]
