# Generated by Django 4.0.5 on 2022-08-21 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_student_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='solution',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
