# Generated by Django 4.0.5 on 2022-08-26 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_task_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.student'),
        ),
    ]
