# Generated by Django 4.0.5 on 2022-08-21 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_task_solution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='courses',
        ),
    ]
