# Generated by Django 4.0.5 on 2022-08-27 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_solution_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
