# Generated by Django 4.0.5 on 2022-08-21 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_student_courses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'managed': False},
        ),
    ]
