# Generated by Django 4.0.5 on 2022-08-21 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_student_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
    ]
