# Generated by Django 4.0.5 on 2022-08-21 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='solution',
        ),
        migrations.CreateModel(
            name='SolutionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution', models.FileField(blank=True, null=True, upload_to='')),
                ('name', models.CharField(blank=True, max_length=2000, null=True)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.task')),
            ],
        ),
    ]
